version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: Java_Projekt_151898
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: SUPER_SECRET_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Java_Projekt_151898
      SPRING_DATASOURCE_USERNAME: ADMIN
      SPRING_DATASOURCE_PASSWORD: SUPER_SECRET_PASSWORD
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data: 